version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
      - static_volume:/usr/src/backend/django_static
    env_file:
      - ./frontend/.env
    networks:
      - server
    restart: always
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
    - react_build:/frontend/build
    env_file:
      - ./frontend/.env
    networks:
      - server

  nginx:
    container_name: web_server
    image: nginx
    ports:
      - 80:8080
      - 443:443
    volumes:
      - ./ssl/certs:/etc/nginx/certs
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/react
      - static_volume:/var/www/react/django_static
    networks:
      - server
    restart: always
    depends_on:
    - backend
    - frontend

  db:
    container_name: postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./frontend/.env
    networks:
      - server
    restart: always


networks:
  server:

volumes:
  react_build:
  static_volume:
  postgres_data:
  
